name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: Env1

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install chromium

    - name: Run Playwright tests
      run: npx playwright test
      env:
        USERNAME_N: ${{ secrets.USERNAME_N }}
        PWD_N: ${{ secrets.PWD_N }}
        USERNAME_A: ${{ secrets.USERNAME_A }}
        PWD_A: ${{ secrets.PWD_A }}

    - name: Adding Test Report Comment
      if: always()
      uses: dorny/test-reporter@v3
      with:
        name: Test Reporter Comment
        path: test-results/results.xml
        reporter: jest-junit

    - name: Uploading Playwright Report  
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: Playwright Test Report
        path: playwright-report/
        retention-days: 7
    
    - name: Uploading Monocart Test Report
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: Monocart Test Report
        path: monocart-report/
        retention-days: 7
    
    - name: Uploading Test Snapshots
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: Test Snapshots
        path: tests/**/*.png
        retention-days: 7